### ISSUE TITLE
Once you make an invalid mathematical expression, you can't reset

### ISSUE THREAD

**Issue by IroncladDev** [5alid-shammout/rl-calc#1]
I tried to divide something by zero.  After that, I couldn't calculate anything.  Maybe check if the result is NAN and if it is clear it after a second.

**Comment by 5alidshammout** [comment]
Ok, thanks for telling me about that

**Comment by 5alidshammout** [comment]
@Conner1115 is this sentence right???
I'm not awesome at math yet😥

x = any number
x / x = 1

**Comment by IroncladDev** [comment]
Yeah, it's mathematically right unless x is zero

**Comment by 5alidshammout** [comment]
@Conner1115  thanks for solving this sentence!
